### ISSUE TITLE
Support for sfillib?

### ISSUE THREAD

**Issue by ghost** [BtheDestroyer/SpriteTools#4]
Could sfillib be implemented to the project, so you don't have to save your images as .c files?

**Comment by Bryce-Dixon** [comment]
Technically, the rendering of SpriteTools is handled entirely by SF2D right now meaning you could just use sfillib and have it return `st_spritesheet`s. It seems like a pretty easy implementation, though, so I'll probably add a few functions in the next version.

**Comment by Bryce-Dixon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add sfillib support](https://trello.com/c/IL0w4vra/112-add-sfillib-support)

**Comment by ghost** [comment]
Yeah, I figured it'd be easy to implement but it'd be a good idea to use sfillib by default.

**Comment by Bryce-Dixon** [comment]
Update: I just took an hour to install sfillib and it's dependencies. When it's implemented (probably in 2.2 release or 2.3 release) I'll include something in the library's Makefile that automatically downloads and installs the other needed libraries (when it's allowed by their licenses) to save everyone time.

**Comment by Bryce-Dixon** [comment]
All done as of [commit d379a60fd8beb2a2add5c7898728c5067988a056](https://github.com/BtheDestroyer/SpriteTools/commit/d379a60fd8beb2a2add5c7898728c5067988a056).
